import Link from 'next/link'
import React from 'react'

const Footer = () => {
  return (
    <Link href={"https://www.linkedin.com/in/ozgur-cokceken"} target='_blank' className="text-center border-t border-slate-400 w-full pt-8 mt-12">
      generated by zgr  
    </Link>
  )
}

export default Footer